### ISSUE TITLE
No option to adjust opacity in color picker

### ISSUE THREAD

**Issue by Valachio** [TommyAndy/health-notifications#1]
There is no Opacity option in the color picker. This is problematic since this plugin is an overlay and Opacity setting is the most important. If I adjust the color at all, it will become a solid color which will completely block out the screen. The only fix is to reset the plugin and not touch the color picker.

I'm MacOS (M2 Macbook Air).

**Comment by TommyAndy** [comment]
Fixing in https://github.com/runelite/plugin-hub/pull/4158, sorry about that

**Comment by TommyAndy** [comment]
Had some issues with the build after updating some gradle deps, https://github.com/runelite/plugin-hub/pull/4187 should have the fix
