### ISSUE TITLE
Request: Can you make one of these for prayer, or add it to this plugin?

### ISSUE THREAD

**Issue by popekappa** [TommyAndy/health-notifications#2]
The same exact overlay but for low prayer points would be so cool. Is that possible?

Thanks so much for the great plugin!!

**Comment by TommyAndy** [comment]
Yeah, I'll take a look this weekend and let you know

**Comment by popekappa** [comment]
Awesome!! As an additional idea (if it's not a huge ask) if both hp and prayer are low, could a 3rd color be selected for that? It's so nice for when things get hectic and you're dodging lightning on wardens and don't realize you missed a prayer flick. The prayer version would be so nice for barraging/chinning. Absolutely love the plugin!

**Comment by TommyAndy** [comment]
Added a prayer option and a combo overlay option in https://github.com/runelite/plugin-hub/pull/4263, might take a week or two to get merged into Runelite fully, but should be what you're after! Let me know what you think!

**Comment by popekappa** [comment]
Oh wow, that is such a quick turnaround! I will absolutely test it as soon as I see it pop up. Thank you again!

**Comment by popekappa** [comment]
I've been testing it out all weekend -- it's already saved me twice from when my prayer has gotten low! Absolutely love the new functionality. Kudos for the fantastic plugin :D 

Edit: I'm not sure if I'm responsible for closing the issue since I opened it, or if you do that since it's your repo. If you need any action from me I'm happy to do so!

**Comment by TommyAndy** [comment]
Ha, either way works :) I'll close it out, enjoy!

I'm always looking for new ideas, so let me know if you have an idea for a plugin or updates

**Comment by popekappa** [comment]
Hope this doesn't reopen the issue (if it does, feel free to immediately close!) -- just wanted to sing your praises once more! Started playing again after a dry spell, and your plugin is just so clutch. For "afk" slayer notifying me when I need to eat/drink prayer potions is amazing. Not losing track of my hp/prayer during a boss fight is amazing (looking at you KQ!). It's completely changed the way I play the game, I'm way more willing to go out and learn new PVM challenges. Thanks so much for making & improving it!
