### ISSUE TITLE
Prayer notification infinitely activating

### ISSUE THREAD

**Issue by ShadowNekoG** [TommyAndy/health-notifications#3]
When prayer goes below the set threshold it will infinitely send notifications when the game isn't in focus where as going below the hitpoint threshold will only send a notification one time.

**Comment by TommyAndy** [comment]
Ah, I see the issue, will get it fixed

**Comment by TommyAndy** [comment]
https://github.com/runelite/plugin-hub/pull/6497

**Comment by NikoWZRD** [comment]
I realize you just fixed this - But this was accidentally a life saving feature for when you're *really* AFKing slayer.. Is it a huge ask to get this reimplemented as an option for prayer (and maybe health?) lol

**Comment by TommyAndy** [comment]
Yeah, I almost added the option when I "fixed" it because I figured someone might've been using it as a feature :). I'll add a toggle for both prayer and health that will make it keep re-notifying.

**Comment by NikoWZRD** [comment]
You're the best, I really really appreciate that haha

**Comment by wolfsilver00** [comment]
> Yeah, I almost added the option when I "fixed" it because I figured someone might've been using it as a feature :). I'll add a toggle for both prayer and health that will make it keep re-notifying.

Yes please, I actually thought it was bugged on the HP side.. I thought it was intended for it to spam (I mean.. Its an alert, it kind of makes sense)
